AllCops:
  Exclude:
    - 'config/initializers/devise.rb'
    - 'db/**.*'

Layout/DefEndAlignment:
  Exclude:
    - 'app/controllers/api/v1/dishes_controller.rb'


Metrics/AbcSize:
  Max: 19


Metrics/BlockLength:
  Max: 38


Metrics/MethodLength:
  Max: 20


Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/api/v1/categories_controller.rb'
    - 'app/controllers/api/v1/dishes_controller.rb'
    - 'test/test_helper.rb'

Style/Documentation:
  Enabled: false


Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'


Layout/LineLength:
  Max: 154
